### ISSUE TITLE
Some function are broken after the game update

### ISSUE THREAD

**Issue by BlingCc233** [lamadaemon/phigros-save-manager#1]
- when i use decrypt func , it occurs:

``` 
phigros-save-manager decrypt S-T save-1711515509883.save
Now trying to decrypt save...
node:fs:579
  path = getValidatedPath(path);
         ^
```

- when i use get command , it occurs:
```
phigros-save-manager get S-T
Fetching profile
/Users/ccbling/WebstormProjects/phigros-save-manager/dist/cli.js:248
      throw new PhigrosBinaryParseError("Index exceeds!");
            ^
```

how can i fix them , maybe its 'cause of the version update of phi,

**Comment by lamadaemon** [comment]
Probably is because the game update. Thanks for your report! I will work on this these days.

**Comment by lamadaemon** [comment]
'decrypt' bug has confirmed, and it has no relation to the game update. For the another bug, I cannot reproduce the same issue. If you'd like to provide me your save file, I can do further investigation. Thanks!

**Comment by BlingCc233** [comment]
I've sent my save file , did it help?
